name: Run Collections

on:
  workflow_dispatch:

jobs:
  run_collections:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Node Setup
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install newman and newman-reporter-htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install install-artifact-from-github

      - name: Read collections from file
        id: read_collections
        run: |
          mapfile -t collections_array < ./node/Collection/dyn.txt
          collections=$(IFS=','; echo "${collections_array[*]}")
          echo "::set-output name=collections::$collections"

      - name: Run Postman Collections
        run: |
          collections=${{ steps.read_collections.outputs.collections }}
          IFS=',' read -ra COLLECTIONS <<< "$collections"
          for collection in "${COLLECTIONS[@]}"; do
            echo "Running collection: $collection"
            if [ ${{ job.status }} != 'success' ]; then
              newman run ./node/Campaigns/"$collection".json -e ./node/Campaigns/Env/all-esps-dev-env-28299.json -g ./node/Campaigns/Env/dev-dyn-monitor-globals-env.json --reporters cli,-r htmlextra --reporter-htmlextra-export ./newman/dev_dyn_"$collection"_failed_report.html
            else
              newman run ./node/Campaigns/"$collection".json -e ./node/Campaigns/Env/all-esps-dev-env-28299.json -g ./node/Campaigns/Env/dev-dyn-monitor-globals-env.json --reporters cli,-r htmlextra --reporter-htmlextra-export ./newman/dev_dyn_"$collection"_passed_report.html || true
            fi
          done

      # Upload the contents of the test results directory to the workspace
      - name: Output the run details
        uses: actions/upload-artifact@v3
        with:
          name: dev-amazon-monitor-report
          path: newman
